export const courses = [
    {
        id: 1,
        title: "Financial Security Thinking and Principles Theorys",
        image: "assets/img/courses/1.jpg",
        price: "$50.00",
        isFree: true,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/1.jpg"},
        category: "WordPress",
    },
    {
        id: 2,
        title: "Professional Ceramic Moulding for Beginners",
        image: "assets/img/courses/2.jpg",
        price: "$50.00",
        isFree: true,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/2.jpg"},
        category: "JavaScript",
    },
    {
        id: 3,
        title: "Basic Fundamentals of Interior & Graphics Design",
        image: "assets/img/courses/3.jpg",
        price: "$50.00",
        isFree: false,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/3.jpg"},
        category: "React",
    },
    {
        id: 4,
        title: "Photography Crash Course for Photographer",
        image: "assets/img/courses/2.jpg",
        price: "$50.00",
        isFree: false,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/3.jpg"},
        category: "UI / UX Design",
    },
    {
        id: 5,
        title: "WordPress for Beginners – Master WordPress",
        image: "assets/img/courses/5.jpg",
        price: "$50.00",
        isFree: false,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/1.jpg"},
        category: "WordPress",
    },
    {
        id: 6,
        title: "Ultimate Photoshop Training: From Beginner",
        image: "assets/img/courses/6.jpg",
        price: "$50.00",
        isFree: false,
        rating: 5,
        reviews: 21,
        students: 25,
        lessons: 15,
        duration: "1.5 Hours",
        author: {name: "Masum Billah", image: "assets/img/review/2.jpg"},
        category: "Photoshop",
    },
];